# Generated by Django 3.0.5 on 2020-04-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_no', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=150)),
                ('client_address', models.CharField(max_length=200)),
                ('client_email', models.CharField(max_length=100)),
                ('client_registered', models.DateField(auto_now_add=True)),
                ('client_active', models.BooleanField(default=False)),
            ],
        ),
    ]
