# Generated by Django 3.0.5 on 2020-04-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_registered',
            field=models.DateField(),
        ),
    ]
