# Generated by Django 3.0.5 on 2020-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200423_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_ip',
            field=models.CharField(default='0.0.0.0', max_length=20),
        ),
    ]
