# Generated by Django 3.0.5 on 2020-05-12 01:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-status_date'], 'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.AddField(
            model_name='status',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['status_date'], name='client_stat_status__b0b815_idx'),
        ),
    ]
