# Generated by Django 3.0.5 on 2020-05-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20200512_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_date',
            field=models.DateField(),
        ),
    ]
