# Generated by Django 3.0.5 on 2020-05-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20200512_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
