# Generated by Django 3.0.5 on 2020-05-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20200512_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_type',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('TIMED-OUT', 'Time out')], default='OFFLINE', max_length=10),
        ),
    ]
