# Generated by Django 3.0.5 on 2020-05-12 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_status_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
