# Generated by Django 3.0.5 on 2020-05-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_status_status_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_type',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('TIMED-OUT', 'Time out'), ('INTERMITENT', 'Intermitent'), ('ONLINE', 'Online')], default='OFFLINE', max_length=11),
        ),
    ]
